/**
 * Generates the web app's brand assets from brand/identity-logo.svg:
 *   - apps/web/src/components/brand/logoPath.ts  (inline wordmark for React)
 *   - apps/web/public/brand/shards.webp          (dark "crushed glass" card texture)
 *   - apps/web/public/icons/*                    (PWA icons, apple-touch-icon, favicons)
 *   - apps/api/src/db/seed-assets/demo-proof.png (demo payment proof for the seed)
 *
 * To use the official logo, replace brand/identity-logo.svg (single-colour,
 * fill="currentColor" or white) and run `npm run brand`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const root = path.resolve(import.meta.dirname, '../..');
const out = (...parts) => {
  const file = path.join(root, ...parts);
  mkdirSync(path.dirname(file), { recursive: true });
  return file;
};

// ─── Logo ────────────────────────────────────────────────────────────────────

const logoSvg = readFileSync(path.join(root, 'brand/identity-logo.svg'), 'utf8');
const viewBox = /viewBox="([^"]+)"/.exec(logoSvg)[1];
const paths = [...logoSvg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
const [vx, vy, vw, vh] = viewBox.split(/\s+/).map(Number);

writeFileSync(
  out('apps/web/src/components/brand/logoPath.ts'),
  `// Generated by scripts/brand/generate.mjs from brand/identity-logo.svg — do not edit.\n` +
    `export const LOGO_VIEWBOX = '${viewBox}';\n` +
    `export const LOGO_ASPECT = ${(vw / vh).toFixed(4)};\n` +
    `export const LOGO_PATHS = ${JSON.stringify(paths)};\n`,
);

/** The wordmark as an SVG fragment, scaled to `width` and centred at (cx, cy). */
function logoFragment(width, cx, cy, fill = '#fff') {
  const scale = width / vw;
  const height = vh * scale;
  const x = cx - width / 2 - vx * scale;
  const y = cy - height / 2 - vy * scale;
  return `<g transform="translate(${x.toFixed(2)} ${y.toFixed(2)}) scale(${scale.toFixed(5)})">${paths
    .map((d) => `<path fill="${fill}" fill-rule="evenodd" d="${d}"/>`)
    .join('')}</g>`;
}

// ─── Shards texture ──────────────────────────────────────────────────────────

function mulberry32(seed) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const hex = (v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0');
const grey = (v) => `#${hex(v)}${hex(v)}${hex(v)}`;

function shardsSvg(width, height, seed) {
  const rand = mulberry32(seed);
  const defs = [];
  // A small palette of glossy gradients (dark flake with a lighter sheen), reused by every shard.
  const gradients = [];
  for (let i = 0; i < 28; i++) {
    const id = `g${i}`;
    const blue = i >= 24;
    const base = 12 + rand() * 30;
    const sheen = base + 40 + rand() * 85;
    const from = blue ? '#0b1f4d' : grey(base);
    const to = blue ? ['#1f5fd6', '#2f7bff', '#174bb3', '#3d8bff'][i - 24] : grey(sheen);
    defs.push(
      `<linearGradient id="${id}" gradientTransform="rotate(${Math.round(rand() * 360)} .5 .5)">` +
        `<stop offset="0" stop-color="${from}"/><stop offset="${(0.45 + rand() * 0.4).toFixed(2)}" stop-color="${to}"/>` +
        `<stop offset="1" stop-color="${from}"/></linearGradient>`,
    );
    gradients.push({ id, blue });
  }
  const greyGradients = gradients.filter((g) => !g.blue);
  const blueGradients = gradients.filter((g) => g.blue);

  const shard = (sizeMin, sizeMax) => {
    const cx = rand() * width;
    const cy = rand() * height;
    const size = sizeMin + rand() ** 1.8 * (sizeMax - sizeMin);
    const sides = rand() < 0.6 ? 4 : 3;
    const rotation = rand() * Math.PI * 2;
    const squash = 0.45 + rand() * 0.55;
    const points = [];
    for (let k = 0; k < sides; k++) {
      const angle = rotation + (k / sides) * Math.PI * 2 + (rand() - 0.5) * 0.8;
      const r = size * (0.5 + rand() * 0.6);
      points.push(`${(cx + Math.cos(angle) * r).toFixed(1)},${(cy + Math.sin(angle) * r * squash).toFixed(1)}`);
    }
    const blue = rand() < 0.045;
    const pool = blue ? blueGradients : greyGradients;
    const gradient = pool[Math.floor(rand() * pool.length)].id;
    return `<polygon points="${points.join(' ')}" fill="url(#${gradient})" opacity="${(blue ? 0.65 + rand() * 0.3 : 0.75 + rand() * 0.25).toFixed(2)}"/>`;
  };

  const area = width * height;
  const far = Array.from({ length: Math.round(area / 900) }, () => shard(10, 46)).join('');
  const near = Array.from({ length: Math.round(area / 750) }, () => shard(7, 36)).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
<defs>${defs.join('')}
<filter id="depth" x="-5%" y="-5%" width="110%" height="110%"><feGaussianBlur stdDeviation="2.4"/></filter>
<radialGradient id="vignette" cx=".5" cy=".45" r=".75"><stop offset=".35" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".55"/></radialGradient>
</defs>
<rect width="100%" height="100%" fill="#08080a"/>
<g filter="url(#depth)" opacity=".85">${far}</g>
<g stroke="#ffffff" stroke-opacity=".05" stroke-width=".6">${near}</g>
<rect width="100%" height="100%" fill="#000" opacity=".22"/>
<rect width="100%" height="100%" fill="url(#vignette)"/>
</svg>`;
}

const texture = shardsSvg(1000, 640, 42);
await sharp(Buffer.from(texture)).webp({ quality: 74, effort: 6 }).toFile(out('apps/web/public/brand/shards.webp'));

// ─── Icons ───────────────────────────────────────────────────────────────────

const iconTexture = shardsSvg(512, 512, 7);
const textureDataUri = `data:image/png;base64,${(await sharp(Buffer.from(iconTexture)).png().toBuffer()).toString('base64')}`;

function iconSvg(size, { logoRatio, radius = 0, texture = true }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
<defs><clipPath id="c"><rect width="${size}" height="${size}" rx="${radius}"/></clipPath></defs>
<g clip-path="url(#c)">
<rect width="${size}" height="${size}" fill="#000"/>
${texture ? `<image href="${textureDataUri}" xlink:href="${textureDataUri}" width="${size}" height="${size}" opacity=".55"/>` : ''}
<rect width="${size}" height="${size}" fill="#000" opacity=".25"/>
${logoFragment(size * logoRatio, size / 2, size / 2)}
</g></svg>`;
}

/** Lucide "car-front" (ISC licence), drawn white. */
function badgeSvg(size) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
<path d="m21 8-2 2-1.5-3.7A2 2 0 0 0 15.646 5H8.4a2 2 0 0 0-1.903 1.257L5 10 3 8"/><path d="M7 14h.01"/><path d="M17 14h.01"/>
<rect width="18" height="8" x="3" y="10" rx="2"/><path d="M5 18v2"/><path d="M19 18v2"/></svg>`;
}

const icons = [
  ['apps/web/public/icons/icon-192.png', 192, { logoRatio: 0.78 }],
  ['apps/web/public/icons/icon-512.png', 512, { logoRatio: 0.78 }],
  // Maskable icons are cropped to a circle by some launchers: keep the logo in the 80 % safe zone.
  ['apps/web/public/icons/maskable-512.png', 512, { logoRatio: 0.62 }],
  ['apps/web/public/icons/apple-touch-icon.png', 180, { logoRatio: 0.78 }],
  ['apps/web/public/icons/favicon-32.png', 32, { logoRatio: 0.92, radius: 6, texture: false }],
];
for (const [file, size, options] of icons) {
  // Palette PNGs: the icons are nearly monochrome, so 256 colours are plenty and the files stay small.
  await sharp(Buffer.from(iconSvg(size, options)))
    .png({ palette: true, quality: 90, effort: 10, compressionLevel: 9 })
    .toFile(out(file));
}
writeFileSync(
  out('apps/web/public/icons/favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#000"/>${logoFragment(58, 32, 32)}</svg>\n`,
);

// Notification badge (Android status bar): a white car on transparent; only its shape is used.
await sharp(Buffer.from(badgeSvg(96))).png({ compressionLevel: 9 }).toFile(out('apps/web/public/icons/badge-96.png'));

// ─── Demo payment proof (seed data) ──────────────────────────────────────────

const receipt = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="800" viewBox="0 0 600 800">
<rect width="600" height="800" fill="#eef0f3"/>
<rect x="40" y="40" width="520" height="720" rx="18" fill="#fff"/>
<g font-family="Arial, Helvetica, sans-serif" fill="#1c1c1e">
<text x="80" y="120" font-size="34" font-weight="700">Transfer receipt</text>
<text x="80" y="160" font-size="20" fill="#8e8e93">DEMO — not a real payment</text>
<text x="80" y="260" font-size="22" fill="#8e8e93">Amount</text><text x="520" y="260" font-size="26" font-weight="700" text-anchor="end">20.000 DT</text>
<text x="80" y="320" font-size="22" fill="#8e8e93">To</text><text x="520" y="320" font-size="22" text-anchor="end">Identity Car Community</text>
<text x="80" y="380" font-size="22" fill="#8e8e93">Reference</text><text x="520" y="380" font-size="22" text-anchor="end">ENTRY FEE</text>
<text x="80" y="440" font-size="22" fill="#8e8e93">Status</text><text x="520" y="440" font-size="22" fill="#248a3d" font-weight="700" text-anchor="end">Completed</text>
</g>
<line x1="80" y1="200" x2="520" y2="200" stroke="#e5e5ea" stroke-width="2"/>
<line x1="80" y1="490" x2="520" y2="490" stroke="#e5e5ea" stroke-width="2"/>
</svg>`;
await sharp(Buffer.from(receipt)).png({ compressionLevel: 9 }).toFile(out('apps/api/src/db/seed-assets/demo-proof.png'));

console.log('Brand assets generated.');
