import type {
  AnnouncementAudience,
  ChatNotificationMode,
  ClubPlaceCategory,
  Language,
  MeetupVisibility,
  MemberStatus,
  PaymentKind,
  PaymentMethod,
  PaymentStatus,
  Role,
} from '@identity/shared';
import { sql } from 'drizzle-orm';
import {
  type AnyPgColumn,
  boolean,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

const timestamptz = (name: string) => timestamp(name, { withTimezone: true });
const createdAt = () => timestamptz('created_at').notNull().defaultNow();
const updatedAt = () =>
  timestamptz('updated_at')
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  fullName: text('full_name').notNull(),
  /** E.164, e.g. +21620123456. Used to sign in. */
  phone: text('phone').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  car: text('car'),
  /** Ids in `member_photos`, kept here so a member row is enough to describe them. */
  avatarPhotoId: uuid('avatar_photo_id'),
  coverPhotoId: uuid('cover_photo_id'),
  carPhotoIds: jsonb('car_photo_ids').$type<string[]>().notNull().default([]),
  /** Shown on the profile: a short presentation and an Instagram name (without "@"). */
  bio: text('bio'),
  instagram: text('instagram'),
  /** Preferred language (notifications are written in it); null until the app sets it. */
  language: text('language').$type<Language>(),
  /** Last authenticated request, refreshed at most once a minute. */
  lastSeenAt: timestamptz('last_seen_at'),
  /** Club chat: push notifications wanted, last read time (unread badge), last grouped push sent. */
  chatNotifications: text('chat_notifications').$type<ChatNotificationMode>().notNull().default('mentions'),
  chatReadAt: timestamptz('chat_read_at'),
  chatPushedAt: timestamptz('chat_pushed_at'),
  role: text('role').$type<Role>().notNull().default('member'),
  status: text('status').$type<MemberStatus>().notNull().default('pending'),
  /** Assigned when the membership is first activated. */
  badgeNumber: integer('badge_number').unique(),
  /** Last day covered by verified dues. */
  paidUntil: date('paid_until', { mode: 'string' }),
  approvedAt: timestamptz('approved_at'),
  locationSharing: boolean('location_sharing').notNull().default(false),
  /** Incremented to revoke every token issued before. */
  tokenVersion: integer('token_version').notNull().default(0),
  /**
   * The ban running now (history in `member_bans`): until a time (it ends by
   * itself), or for life (no sign-in, devices blocked).
   */
  bannedUntil: timestamptz('banned_until'),
  bannedForever: boolean('banned_forever').notNull().default(false),
  banReason: text('ban_reason'),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/** Every ban given, for the tiers (3, 7, then 15 days) and the admins' history. */
export const memberBans = pgTable(
  'member_bans',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    byId: uuid('by_id').references(() => users.id, { onDelete: 'set null' }),
    /** 1 for a first ban. */
    level: integer('level').notNull(),
    permanent: boolean('permanent').notNull().default(false),
    reason: text('reason'),
    startsAt: timestamptz('starts_at').notNull(),
    /** null for life. */
    endsAt: timestamptz('ends_at'),
    /** Lifted early by an admin: the ban does not count in the tiers. */
    liftedAt: timestamptz('lifted_at'),
    liftedById: uuid('lifted_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: createdAt(),
  },
  (t) => [index('member_bans_user_idx').on(t.userId)],
);

/**
 * Installations of the app each member used (X-Device-Id, generated by the app
 * and kept on the device). The devices of a member banned for life cannot sign
 * in or register a new account.
 */
export const memberDevices = pgTable(
  'member_devices',
  {
    deviceId: text('device_id').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    firstSeenAt: timestamptz('first_seen_at').notNull(),
    lastSeenAt: timestamptz('last_seen_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.deviceId, t.userId] }), index('member_devices_user_idx').on(t.userId)],
);

/** Places shown on the map by the club: meeting spots, partner garages… */
export const clubPlaces = pgTable('club_places', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  category: text('category').$type<ClubPlaceCategory>().notNull(),
  description: text('description'),
  lat: doublePrecision('lat').notNull(),
  lng: doublePrecision('lng').notNull(),
  createdById: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/** Circles where members' positions are never shown. */
export const redZones = pgTable('red_zones', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  /** Why the zone exists, shown to members. */
  description: text('description'),
  lat: doublePrecision('lat').notNull(),
  lng: doublePrecision('lng').notNull(),
  /** Metres. */
  radius: integer('radius').notNull(),
  createdById: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/** Profile and cover photos (one each per member) and car photos, stored through `Storage`. */
export const memberPhotos = pgTable(
  'member_photos',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    kind: text('kind').$type<'avatar' | 'cover' | 'car'>().notNull(),
    file: text('file').notNull(),
    mime: text('mime').notNull(),
    createdAt: createdAt(),
  },
  (t) => [index('member_photos_user_idx').on(t.userId)],
);

/** Latest shared position per member, already snapped to the grid (LOCATION_PRECISION_METERS). */
export const memberLocations = pgTable('member_locations', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  lat: doublePrecision('lat').notNull(),
  lng: doublePrecision('lng').notNull(),
  updatedAt: timestamptz('updated_at').notNull().defaultNow(),
});

export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    kind: text('kind').$type<PaymentKind>().notNull(),
    /** Millimes, fixed when the payment is submitted. */
    amount: integer('amount').notNull(),
    method: text('method').$type<PaymentMethod>().notNull(),
    status: text('status').$type<PaymentStatus>().notNull().default('pending'),
    /** Dues only: first period paid, how many periods, and the period length at the time. */
    periodStart: date('period_start', { mode: 'string' }),
    periodCount: integer('period_count'),
    periodMonths: integer('period_months'),
    proofFile: text('proof_file'),
    proofMime: text('proof_mime'),
    note: text('note'),
    reviewNote: text('review_note'),
    reviewedById: uuid('reviewed_by').references(() => users.id, { onDelete: 'set null' }),
    reviewedAt: timestamptz('reviewed_at'),
    createdAt: createdAt(),
  },
  (t) => [
    index('payments_user_idx').on(t.userId),
    index('payments_status_idx').on(t.status),
    // A member has at most one entry fee that is pending or verified.
    uniqueIndex('payments_entry_fee_once')
      .on(t.userId)
      .where(sql`${t.kind} = 'entry_fee' and ${t.status} <> 'rejected'`),
  ],
);

export const meetups = pgTable(
  'meetups',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    title: text('title').notNull(),
    description: text('description'),
    visibility: text('visibility').$type<MeetupVisibility>().notNull(),
    startsAt: timestamptz('starts_at').notNull(),
    /** Secret meetups: hours before start when confirmed members see the meeting point. */
    revealHoursBefore: integer('reveal_hours_before').notNull().default(2),
    locationName: text('location_name'),
    address: text('address'),
    lat: doublePrecision('lat'),
    lng: doublePrecision('lng'),
    rules: text('rules'),
    hostId: uuid('host_id').references(() => users.id, { onDelete: 'set null' }),
    cancelledAt: timestamptz('cancelled_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('meetups_starts_at_idx').on(t.startsAt)],
);

export const meetupRsvps = pgTable(
  'meetup_rsvps',
  {
    meetupId: uuid('meetup_id')
      .notNull()
      .references(() => meetups.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.meetupId, t.userId] }), index('meetup_rsvps_user_idx').on(t.userId)],
);

export const announcements = pgTable(
  'announcements',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    authorId: uuid('author_id').references(() => users.id, { onDelete: 'set null' }),
    body: text('body').notNull(),
    audience: text('audience').$type<AnnouncementAudience>().notNull().default('all'),
    createdAt: createdAt(),
  },
  (t) => [index('announcements_created_at_idx').on(t.createdAt)],
);

export const notifications = pgTable(
  'notifications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull(),
    title: text('title').notNull(),
    body: text('body'),
    link: text('link'),
    readAt: timestamptz('read_at'),
    createdAt: createdAt(),
  },
  (t) => [index('notifications_user_idx').on(t.userId, t.createdAt)],
);

/** The club chat. Deleted messages keep their row (replies still point to them) but lose their text. */
export const chatMessages = pgTable(
  'chat_messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    authorId: uuid('author_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    body: text('body').notNull(),
    replyToId: uuid('reply_to_id').references((): AnyPgColumn => chatMessages.id, { onDelete: 'set null' }),
    mentions: jsonb('mentions').$type<string[]>().notNull().default([]),
    deletedAt: timestamptz('deleted_at'),
    createdAt: createdAt(),
  },
  (t) => [index('chat_messages_created_at_idx').on(t.createdAt)],
);

/**
 * Web Push subscriptions: one per browser / installed app. The endpoint is
 * unique; signing in with another account on the same device moves it.
 */
export const pushSubscriptions = pgTable(
  'push_subscriptions',
  {
    endpoint: text('endpoint').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    p256dh: text('p256dh').notNull(),
    auth: text('auth').notNull(),
    createdAt: createdAt(),
  },
  (t) => [index('push_subscriptions_user_idx').on(t.userId)],
);

/** Key/value store for club settings (see `clubSettingsSchema`). */
export const settings = pgTable('settings', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: updatedAt(),
});

export type UserRow = typeof users.$inferSelect;
export type PaymentRow = typeof payments.$inferSelect;
export type MeetupRow = typeof meetups.$inferSelect;
export type AnnouncementRow = typeof announcements.$inferSelect;
export type ClubPlaceRow = typeof clubPlaces.$inferSelect;
export type RedZoneRow = typeof redZones.$inferSelect;
